import Provider from '@/utils/lib/provider'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: {
    default: 'Nome do Projeto',
    template: '%s | Nome do site',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-contrastBackgroud`}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
