import Provider from "@/utils/lib/provider";
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/context/elements.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "DevSync",
    template: "%s | DevSync",
  },
  description: "Generated by create next app",
  icons: {
    icon: "/_next/static/media/metadata/favicon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray`}>
        <ThemeProvider>
          <Provider>
            {children}
            </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
